config/routes.rb
Rails.application.routes.draw do
  resources :records

  root 'generator#generator_form'

  post 'generate' => 'generator#generate', as: :generate
  delete 'clean' => 'generator#clean', as: :clean

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_tree
end

app/models/generator.rb
class Generator
  NAMES = ['avael','alexey','smirnov','petr','natali','rachelle','eve','maria','max','barnie','tatiana','lili','grinch','fester','cici','jess','ray','ban','monroe','michael','michelle','ted','gena','ivan','igor','evgeny','nika','daniil','harrison','hanry','hank','iosif','katarina','ryze','shaco','xin','zach','yi']
  WORDS = ["illo", "eveniet", "nisi", "beatae", "et", "culpa", "est", "facere", "quia", "expedita", "iure", "aut", "similique", "quod", "ut", "praesentium", "quo", "eius", "reiciendis", "repellendus", "nam", "ut", "occaecati", "adipisci", "sunt", "est", "eos", "quia", "temporibus", "qui", "recusandae", "quia", "unde", "enim", "et", "error", "rerum", "perferendis", "inventore", "esse", "officiis", "qui", "nihil", "qui", "ab", "excepturi", "et", "distinctio", "dolorem", "soluta", "siemens"] 

  def self.generate(users_count, records_count, comments_count, comments_depth)
    g_u_count = generate_users(users_count)
    g_r_count = generate_records(records_count)
    g_c_count = generate_comments(comments_count, comments_depth)
    return "generate result: users - #{g_u_count}, records - #{g_r_count}, comments - #{g_c_count}"
  end

  private

    def self.generate_users(count)
      return 0 if count.nil? || count == 0
      users = []
      count.times do
        users.push "('#{rand(36**rand(5..8)).to_s(36)}', '#{NAMES.sample}')"
      end
      User.connection.execute "INSERT INTO users (login, name) VALUES #{users.join(", ")}"
      users.count
    end

    def self.generate_records(count)
      return 0 if count.nil? || count == 0
      user_ids = User.all.pluck(:id)
      # faker was a bad idea - for now, speed test shows a ±3x speedup with my own sentenses maker
      # par = Faker::Lorem.paragraphs(count)
      # sent = Faker::Lorem.sentences(count)
      records = []
      count.times do |i|
        records.push "('#{generate_sentenses(1)}', '#{generate_sentenses(rand(1..5))}', #{user_ids.sample})"
      end
      records.each_slice(10000).to_a.each do |records|
        Record.connection.execute "INSERT INTO records (title, body, owner_id) VALUES #{records.join(", ")}"
      end
      records.count
    end

    def self.generate_comments(count, depth)
      return 0 if count.nil? || count == 0
    end

    def self.generate_sentenses(count)
      sentenses = []
      count.times do
        words = []
        rand(4..8).times do
          words << WORDS.sample
        end
        sentenses << words.join(" ").capitalize+"."
      end
      sentenses.join(" ")
    end

end

app/models/record.rb
class Record < ActiveRecord::Base
  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/generator_controller.rb
class GeneratorController < ApplicationController

  def generator_form
  end

  def generate
    result = nil
    time = Benchmark.ms do
      result = Generator.generate(params[:users_count].to_i,params[:records_count].to_i,params[:comments_count].to_i,params[:comments_depth].to_i)
    end
    redirect_to :root, notice: result+", time spent: #{time}"
  end

  def clean
    Comment.delete_all
    Record.delete_all
    User.delete_all
    redirect_to :root, notice: 'successfully cleaned up!'
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  def index
    @records = Record.all
  end

  # GET /records/1
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  def create
    @record = Record.new(record_params)

    if @record.save
      redirect_to @record, notice: 'Record was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /records/1
  def update
    if @record.update(record_params)
      redirect_to @record, notice: 'Record was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /records/1
  def destroy
    @record.destroy
    redirect_to records_url, notice: 'Record was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def record_params
      params.require(:record).permit(:owner_id, :title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/generator/generator_form.html.slim
h1 welcome to generator!

div.stats
  h4 stats:
  | users:
  = User.count
  br
  | records:
  = Record.count
  br
  | comments:
  = Comment.count
  br
  br

- if flash[:notice]
  .alert.alert-success #{flash[:notice]}
  br
  br

= link_to 'cleanup!', :clean, method: :delete
br
br

= form_tag :generate do |f|
  div.field
    = label_tag :users_count
    br
    = number_field_tag :users_count
  div.field
    = label_tag :records_count
    br
    = number_field_tag :records_count
  div.field
    = label_tag :comments_count
    br
    = number_field_tag :comments_count
  div.field
    = label_tag :comments_depth
    br
    = number_field_tag :comments_depth
  div.actions
    = submit_tag

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestEgoCms</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/records/_form.html.slim
= form_for @record do |f|
  - if @record.errors.any?
    #error_explanation
      h2 = "#{pluralize(@record.errors.count, "error")} prohibited this record from being saved:"
      ul
        - @record.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :owner_id
    = f.number_field :owner_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions = f.submit 'Save'

app/views/records/edit.html.slim
h1 Editing record

== render 'form'

= link_to 'Show', @record
'|
= link_to 'Back', records_path

app/views/records/index.html.slim
h1 Listing records

table
  thead
    tr
      th Owner
      th Title
      th Body
      th
      th
      th

  tbody
    - @records.each do |record|
      tr
        td = record.owner_id
        td = record.title
        td = record.body
        td = link_to 'Show', record
        td = link_to 'Edit', edit_record_path(record)
        td = link_to 'Destroy', record, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Record', new_record_path

app/views/records/new.html.slim
h1 New record

== render 'form'

= link_to 'Back', records_path

app/views/records/show.html.slim
p#notice = notice

p
  strong Owner:
  = @record.owner_id
p
  strong Title:
  = @record.title
p
  strong Body:
  = @record.body

= link_to 'Edit', edit_record_path(@record)
'|
= link_to 'Back', records_path